//массив карточек разных брендов

export let brandCardsArray = [
  {
    name: "lenovo",
    link: "#",
    image: "src/img/img-slider-of-brands/Lenovo.png",
    imageWidth: "108px",
    imageHeight: "32px",
    alt: "Логотип Леново",
    purpose: "brand",
  },
  {
    name: "samsung",
    link: "#",
    image: "src/img/img-slider-of-brands/Samsung.png",
    imageWidth: "116px",
    imageHeight: "38.5px",
    alt: "Логотип Самсунг",
    purpose: "brand",
  },
  {
    name: "apple",
    link: "#",
    image: "src/img/img-slider-of-brands/Apple.png",
    imageWidth: "44px",
    imageHeight: "44px",
    alt: "Логотип Эппл",
    purpose: "brand",
  },
  {
    name: "view-sonic",
    link: "#",
    image: "src/img/img-slider-of-brands/ViewSonic.png",
    imageWidth: "128px",
    imageHeight: "21px",
    alt: "Логотип Вью Соник",
    purpose: "brand",
  },
  {
    name: "bosch",
    link: "#",
    image: "src/img/img-slider-of-brands/Bosch.png",
    imageWidth: "128px",
    imageHeight: "28.6px",
    alt: "Логотип Бош",
    purpose: "brand",
  },
  {
    name: "hp",
    link: "#",
    image: "src/img/img-slider-of-brands/HP.png",
    imageWidth: "52px",
    imageHeight: "52px",
    alt: "Логотип Эйч Пи",
    purpose: "brand",
  },
  {
    name: "acer",
    link: "#",
    image: "src/img/img-slider-of-brands/Acer.png",
    imageWidth: "94px",
    imageHeight: "24px",
    alt: "Логотип Эйсер",
    purpose: "brand",
  },
  {
    name: "sony",
    link: "#",
    image: "src/img/img-slider-of-brands/Sony.png",
    imageWidth: "128px",
    imageHeight: "26.6px",
    alt: "Логотип Сони",
    purpose: "brand",
  },
];
